### PR TITLE
Fix wasm examples

### LINKED ISSUE #336: [Bug] WASM Node.js examples broken
## Bug description
Most of the WASM Node.js examples throw errors when run on the latest `dev` branch:

- `create_did`: works ✓
- `create_vc`: ❌
- `create_vp`: ❌
- `manipulate_did`: ❌
- `merkle_key`: ❌
- `resolution`: ❌
- `revocation`: ❌

This issue was originally reported on the Discord identity-discussion channel.

## Language version

Using the WASM bindings for Node.js.

- Language: Rust v1.53.0
- Language: Node.js v14.17.3

## IOTA Identity version
Which version of IOTA Identity are you using?

- Version (version number, commit, or branch): `dev` branch (commit 7b07d50646f7c919143ee0d0fbdbe6d0bde328c8)

## Hardware specification
What hardware are you using? (Delete if not relevant)

- Operating system: Windows 10 19043.1149 / Ubuntu 20.04
- RAM: 16GB
- Cores: 12/24
- Device: desktop AMD CPU (shouldn't matter)

## Steps To reproduce the bug

1. Checkout the latest version of `identity.rs` on the `dev` branch (commit 7b07d50646f7c919143ee0d0fbdbe6d0bde328c8 at time of writing)
2. Build the Node.js WASM bindings:
    ```bash
    cd bindings/wasm
    npm install
    npm run build:nodejs
    ```
3. Run any of the broken examples listed above, e.g. `npm run example:node -- create_vc`

## Expected behaviour

All WASM/Node.js examples should run without errors when executing `npm run example:node -- all`

## Actual behaviour

Most Node.js examples throw an error.

## Errors

The errors for all examples are the same, with `passStringToWasm0`/`Document.set previousMessageId` causing the error.

```
 npm run example:node -- create_vc

> @iota/identity-wasm@0.3.4 example:node C:\<snip>\identity.rs\bindings\wasm
> node examples/node/node.js "create_vc"

Identity Creation: https://explorer.iota.org/mainnet/transaction/[object Object]
Identity Creation: https://explorer.iota.org/mainnet/transaction/[object Object]
Err > RuntimeError: memory access out of bounds
    at dlmalloc::dlmalloc::Chunk::size::h477966db562662ed (<anonymous>:wasm-function[4821]:0x307492)
    at __rdl_realloc (<anonymous>:wasm-function[799]:0x1f82f7)
    at __rust_realloc (<anonymous>:wasm-function[4297]:0x3054f9)
    at __wbindgen_realloc (<anonymous>:wasm-function[4099]:0x303cd5)
    at passStringToWasm0 (C:\Work\iota\identity.rs\bindings\wasm\node\identity_wasm.js:89:15)
    at Document.set previousMessageId [as previousMessageId] (C:\<snip>\identity.rs\bindings\wasm\node\identity_wasm.js:1300:20)
    at manipulateIdentity (C:\<snip>\identity.rs\bindings\wasm\examples\node\manipulate_did.js:46:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async createVC (C:\<snip>\identity.rs\bindings\wasm\examples\node\create_vc.js:25:20)
    at async main (C:\<snip>\identity.rs\bindings\wasm\examples\node\node.js:29:20)   
```

### PR DESCRIPTION
**Pull request by l1h3r**
# Description of change

Use 🐪 case when serializing `Receipt` as JSON. Fixes `messageId` usage in JavaScript examples.

## Links to any relevant issues

Closes #336

## Type of change

- [x] Bug fix (a non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested
Describe the tests that you ran to verify your changes.
Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist
Add an `x` to the boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by cycraig — CHANGES_REQUESTED** [review]
This fixes most usages of `messageId` in the Wasm examples but not all. Note the error for `bindings/wasm/examples/node/revocation.js` below, and some explorer URLs containting `[object Object]`.

Output of `npm run example:node -- all`:
```
> @iota/identity-wasm@0.3.4 example:node C:\Work\iota\identity.rs\bindings\wasm
> node examples/node/node.js "all"

>>> Run All Examples
Identity Creation: https://explorer.iota.org/mainnet/transaction/a3f9fa58bf95b007548a1a9726aceecfe13f5b6eb915084a22243b803445de8b
Identity Creation: https://explorer.iota.org/mainnet/transaction/96d811c815bfcb2e66b5dc5b47948c9cf1393eeabccaa537ee6e454d525635db
Identity Update: https://explorer.iota.org/mainnet/transaction/[object Object]
Identity Creation: https://explorer.iota.org/mainnet/transaction/774945cf0436a4ed2b5b0d02129dd14addae2e49386d6ab0ac9480f6df325c8e
Identity Update: https://explorer.iota.org/mainnet/transaction/[object Object]
Identity Creation: https://explorer.iota.org/mainnet/transaction/35646254e2769fdc3d6eb99ada30fa209d7af292837dca4f50b5ce7456367664
Identity Creation: https://explorer.iota.org/mainnet/transaction/17dd742c7925be944f40d6029219ea9a4643641c523dff69f5df099e72c692d6
Identity Update: https://explorer.iota.org/mainnet/transaction/[object Object]
VC verification result: true
Identity Creation: https://explorer.iota.org/mainnet/transaction/49ea4aefb6e91334d799dc7c4d1a8d6d19ca2cb3aa346d4affcc738844b56898
Identity Creation: https://explorer.iota.org/mainnet/transaction/b0ba74de57e160c9ebc1db6b776f95b7ce5b50de0204c6f85ce2192fbf8978ae
Identity Update: https://explorer.iota.org/mainnet/transaction/[object Object]
VC verification result: true
Err > RuntimeError: memory access out of bounds
    at dlmalloc::dlmalloc::Chunk::size::h477966db562662ed (<anonymous>:wasm-function[4823]:0x306a4a)
    at __rdl_realloc (<anonymous>:wasm-function[797]:0x1f7790)
    at __rust_realloc (<anonymous>:wasm-function[4298]:0x304aa6)
    at __wbindgen_realloc (<anonymous>:wasm-function[4099]:0x303261)
    at passStringToWasm0 (C:\Work\iota\identity.rs\bindings\wasm\node\identity_wasm.js:89:15)
    at Document.set previousMessageId [as previousMessageId] (C:\Work\iota\identity.rs\bindings\wasm\node\identity_wasm.js:1300:20)
    at revoke (C:\Work\iota\identity.rs\bindings\wasm\examples\node\revocation.js:36:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (C:\Work\iota\identity.rs\bindings\wasm\examples\node\node.js:43:13) 
```

File: bindings/wasm/examples/node/revocation.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ async function revoke(clientConfig) {
     issuer.doc.removeMethod(DID.parse(issuer.doc.id.toString()+"#newKey"));
     issuer.doc.previousMessageId = issuer.nextMessageId;
```
Comment (cycraig) [inline bindings/wasm/examples/node/revocation.js:36]: `issuer.nextMessageId` is also a receipt. It might be better to explicitly rename all existing `messageId` instances to `messageReceipt` to avoid confusion.

**Review by cycraig — APPROVED** [review]
All examples run. Looks good to me!

The final "Err > Unknown example name" is just due to a fallthrough to the default in the example runner's switch statement, not a real error (and not worth delaying this PR).
```
npm run example:node -- all

> @iota/identity-wasm@0.3.4 example:node C:\Work\iota\identity.rs\bindings\wasm
> node examples/node/node.js "all"

>>> Run All Examples
Identity Creation: https://explorer.iota.org/mainnet/transaction/25f63d76a5783e7db299dfbc1ae0aea27c988dbe2d95e31f50e34f0db9bc3a5d
Identity Creation: https://explorer.iota.org/mainnet/transaction/c26491fbcbe139c6b05de7f0db761516de3a5b4647ec100633dacdf5ad77bce6
Identity Update: https://explorer.iota.org/mainnet/transaction/be9105a512c0d6aecf938ceeced970a2e6ff0bdc63e5223b86f7cd836b456a7d
Identity Creation: https://explorer.iota.org/mainnet/transaction/45c72ceb631ba9b02e6eda96604e5050c5e32c4d1a9d0968eb5a2146f5cdbfa6
Identity Update: https://explorer.iota.org/mainnet/transaction/f67efe142c9e105ccd017bbb9e5fc0cf79c4713f94a816f81ccfdc2252ddb95a
Identity Creation: https://explorer.iota.org/mainnet/transaction/3134c15db54da9bc72e48db459c1598e8c9025c7028efc882ff1ccb8c237d144
Identity Creation: https://explorer.iota.org/mainnet/transaction/77e31a3a3b1a11514dd1b2b8e5bb7c07b869de4262fe24505440abe8cb0e80ba
Identity Update: https://explorer.iota.org/mainnet/transaction/fb4d9d0f6dc646739a231303c7c7d495faeaa9cf3a48144590b4e231960062ff
VC verification result: true
Identity Creation: https://explorer.iota.org/mainnet/transaction/bc24fc34598ae5c39a2b939bfdf0a86c60785910e33b6991f08641ad57d9e57a
Identity Creation: https://explorer.iota.org/mainnet/transaction/99e2ecb16ff4fc74ebedbc6dad8127cc0b22f9b853d3ee76bad39f8de5e7e009
Identity Update: https://explorer.iota.org/mainnet/transaction/2d44460f796c0bd8d225695b30b5ee452b002ee6ed0a18a1f6fc50109d1a0df7
VC verification result: true
Identity Update: https://explorer.iota.org/mainnet/transaction/81b40727d4c556fcec83909cb73981100314a2dc8b21e9a937adc13cf93f8d07
VC verification result: false
Identity Creation: https://explorer.iota.org/mainnet/transaction/4facb0f419ee194394419cf5e244d7498d2e471865c2addf1f8ed40570bc2f08
Identity Creation: https://explorer.iota.org/mainnet/transaction/68b95a7b189cb8f612ffb22c41bb6b2ce7d4f504ea804c5ec205f0a5d4550fbe
Identity Update: https://explorer.iota.org/mainnet/transaction/5b3b022e0178fb917ede9da87c51b1787a00da84a3c911becd652a835d4bcb50
VC verification result: true
VP verification result: true
Identity Creation: https://explorer.iota.org/mainnet/transaction/173bb24e2392a2e5d7e1fe40814abd8054ccd0d28572da3311d4e0b4dd65884e
Identity Creation: https://explorer.iota.org/mainnet/transaction/63f946ba498f740d1288a2bf46355ef8b4781e7e3b7e70dcd546c78441102462
Identity Update: https://explorer.iota.org/mainnet/transaction/aabeddf9b22f168eec3277f66df48c39c102bed2d89445d841edc1ff5483b1b3
VC verification result: true
Identity Update: https://explorer.iota.org/mainnet/transaction/d7521feb74fda6e408d2f26d20c4168690c601ac9ada1a53fcd445168786d45a
VC verification result: true
>>> End All Examples
Err > Unknown example name     
```
